name: yolov4

dependencies:
  - python=3.6.10
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - imutils==0.5.3
      keras==2.3.1
      matplotlib==3.2.1
      numpy==1.18.4
      opencv-python==4.2.0.34
      pillow==7.1.2
      scikit-learn==0.23.1
      scipy==1.4.1
      tensorboard==2.2.1
      tensorflow==2.0.0
      tensorflow-estimator==2.1.0
      tensorflow-gpu==2.2.0
